### ISSUE TITLE
Datos personales Contacto

### ISSUE THREAD

**Issue by ondoheer** [Via-Codigo/charo-zapater-hoker#10]
En la página de contacto quieren que en vez de dirección diga redes y que ellas puedan agregar redes
Hay que agregarles los íconos de fontwaesome  al lado del nombre de red. Subo imágen burda de como quedaría
![screenshot_20190111_162529](https://user-images.githubusercontent.com/3681300/51061501-87a32c00-15c1-11e9-80e2-6e9384c7dd33.png)

**Comment by nramirezsalas** [comment]
Se agregó fontawesome a las redes. 
Con el cliente se revisará para colocar los teléfonos y correo.
