### ISSUE TITLE
Videos en lightbox

### ISSUE THREAD

**Issue by ondoheer** [Via-Codigo/charo-zapater-hoker#12]
Hay que confirmar que pueden subir videos (y ver como se muestran) en las galerías, ya que performance tiene dos videos, deben tener un thumbnail y al hacerlo crecer sale en video en el lightbox

**Comment by nramirezsalas** [comment]
Según la documentación soporta video: youtube y vimeo.
En Performance agregué un item de prueba con video de YouTube para el thumbnail se podría usar la misma imagen que suben actualmente. Lo revisaré con el cliente.
