### ISSUE TITLE
Grid de imágenes

### ISSUE THREAD

**Issue by ondoheer** [Via-Codigo/charo-zapater-hoker#5]
* Las galerías no deben ser full width, cambiar clase container-fluid por container
* Hacer que las fotos sean más cuadradas, darles 400px de alto
* Hacer que haya un margen entre las fotos (más aire) adjunto imágen pero en esta imagen hay demasiada distancia entre las rows
![screencapture-charozapater-demo-codigoux-pinturas-2019-01-11-16_03_50](https://user-images.githubusercontent.com/3681300/51061303-d69c9180-15c0-11e9-9f4f-83e47f1b836f.png)

**Comment by nramirezsalas** [comment]
Galerías internas actualizadas.
