### ISSUE TITLE
Slider Home

### ISSUE THREAD

**Issue by ondoheer** [Via-Codigo/charo-zapater-hoker#8]
Quieren que la imágen principal del home sea un slider contínuo como el de su web actual

http://charo-zapater.com

**Comment by nramirezsalas** [comment]
Probaré esto: https://css-tricks.com/infinite-all-css-scrolling-slideshow/

**Comment by nramirezsalas** [comment]
Quedó bien, faltaría definir bien la imagen o conjunto de imágenes como en su web de flash.
