### ISSUE TITLE
Quitar título de sección CV

### ISSUE THREAD

**Issue by ondoheer** [Via-Codigo/charo-zapater-hoker#9]
Adjunto imagen de como debe quedar

En el módulo CV quitar el doble título y hacerlo como en la imagen tomada (quitar el que dice charo zapater pomar/roman

![charo-cv](https://user-images.githubusercontent.com/3681300/51061452-5cb8d800-15c1-11e9-9dc1-33cc34c0f613.png)

**Comment by nramirezsalas** [comment]
CV actualizado, se quitó el doble título.
